"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useParams} from "next/navigation";
import {createClient} from "@supabase/supabase-js";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
type Lesson={id:string;title:string;content:string|null;sort_order:number;module_id:string|null};
type Module={id:string;title:string;description:string|null;sort_order:number};
export default function CoursePage(){const{id}=useParams<{id:string}>();const[course,setCourse]=useState<any>(null);const[modules,setModules]=useState<Module[]>([]);const[lessons,setLessons]=useState<Lesson[]>([]);const[enrolled,setEnrolled]=useState(false);const[progress,setProgress]=useState<Record<string,boolean>>({});const[message,setMessage]=useState("");const[open,setOpen]=useState<string|null>(null);
useEffect(()=>{if(!id)return;(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return;}const[c,m,l,e,p]=await Promise.all([supabase.from("courses").select("*").eq("id",id).single(),supabase.from("course_modules").select("*").eq("course_id",id).order("sort_order"),supabase.from("lessons").select("*").eq("course_id",id).order("sort_order"),supabase.from("enrollments").select("id").eq("course_id",id).eq("student_id",user.id).maybeSingle(),supabase.from("lesson_progress").select("lesson_id,completed").eq("student_id",user.id)]);setCourse(c.data);setModules(m.data??[]);setLessons(l.data??[]);setEnrolled(!!e.data);const map:Record<string,boolean>={};(p.data??[]).forEach((x:any)=>map[x.lesson_id]=x.completed);setProgress(map)})()},[id]);
async function enroll(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{error}=await supabase.from("enrollments").insert({student_id:user.id,course_id:id});if(error)setMessage(error.message);else{setEnrolled(true);setMessage("You are enrolled in this course.");}}
async function toggleLesson(lesson:Lesson){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const completed=!progress[lesson.id];await supabase.from("lesson_progress").upsert({student_id:user.id,lesson_id:lesson.id,completed,completed_at:completed?new Date().toISOString():null},{onConflict:"student_id,lesson_id"});setProgress({...progress,[lesson.id]:completed});}
if(!course)return <main className="container"><div className="card" style={{marginTop:70}}>Loading course...</div></main>;
return <main className="container"><nav className="nav"><Link href="/courses" className="brand">Skill<span>Arc</span></Link><Link href="/dashboard" className="btn">Dashboard</Link></nav><section className="page-head"><div className="eyebrow">{course.category??"Course"} · {course.level}</div><h1>{course.title}</h1><p>{course.description}</p>{!enrolled&&<button className="btn primary" onClick={enroll}>Enroll in course</button>}{message&&<div className="notice">{message}</div>}</section><div className="stack">{modules.map(m=><article className="card" key={m.id}><button className="module-button" onClick={()=>setOpen(open===m.id?null:m.id)}><span><b>{m.title}</b><small>{m.description}</small></span><span>{open===m.id?"−":"+"}</span></button>{open===m.id&&<div className="lesson-list">{lessons.filter(l=>l.module_id===m.id).map(l=><div className="lesson" key={l.id}><div><b>{l.title}</b><p>{l.content}</p></div><button className={"btn "+(progress[l.id]?"done":"")} onClick={()=>toggleLesson(l)}>{progress[l.id]?"Completed":"Mark complete"}</button></div>)}</div>}</article>)}</div></main>}