"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {useParams} from "next/navigation";import {createClient} from "@supabase/supabase-js";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
export default function CoursePage(){const{id}=useParams<{id:string}>();const[course,setCourse]=useState<any>(null),[modules,setModules]=useState<any[]>([]),[lessons,setLessons]=useState<any[]>([]),[enrolled,setEnrolled]=useState(false),[progress,setProgress]=useState<Record<string,boolean>>({}),[message,setMessage]=useState(""),[open,setOpen]=useState<string|null>(null),[role,setRole]=useState("");
async function load(){if(!id)return;const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return;}const p=await supabase.from("profiles").select("role").eq("id",user.id).single();setRole(p.data?.role??"student");const[c,m,l,e,pr]=await Promise.all([supabase.from("courses").select("*").eq("id",id).single(),supabase.from("course_modules").select("*").eq("course_id",id).order("sort_order"),supabase.from("lessons").select("*").eq("course_id",id).order("sort_order"),supabase.from("enrollments").select("id").eq("course_id",id).eq("student_id",user.id).maybeSingle(),supabase.from("lesson_progress").select("lesson_id,completed").eq("student_id",user.id)]);setCourse(c.data);setModules(m.data??[]);setLessons(l.data??[]);setEnrolled(!!e.data);const map:any={};(pr.data??[]).forEach((x:any)=>map[x.lesson_id]=x.completed);setProgress(map);}
useEffect(()=>{load()},[id]);
async function enroll(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{error}=await supabase.from("enrollments").insert({student_id:user.id,course_id:id});setMessage(error?error.message:"You are enrolled in this course.");if(!error)setEnrolled(true)}
async function toggleLesson(l:any){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const completed=!progress[l.id];const{error}=await supabase.from("lesson_progress").upsert({student_id:user.id,lesson_id:l.id,completed,completed_at:completed?new Date().toISOString():null},{onConflict:"student_id,lesson_id"});if(!error)setProgress({...progress,[l.id]:completed});}
async function addModule(){if(!course)return;const title=prompt("Module title");if(!title)return;const{error}=await supabase.from("course_modules").insert({course_id:id,title,sort_order:modules.length+1});setMessage(error?error.message:"Module added.");if(!error)load();}
async function addLesson(moduleId:string){const title=prompt("Lesson title");if(!title)return;const content=prompt("Lesson content (short text)");const count=lessons.filter(l=>l.module_id===moduleId).length;const{error}=await supabase.from("lessons").insert({course_id:id,module_id:moduleId,title,content,sort_order:count+1});setMessage(error?error.message:"Lesson added.");if(!error)load();}
if(!course)return <main className="container"><div className="card" style={{marginTop:70}}>Loading course...</div></main>;
const canEdit=["instructor","admin","super_admin"].includes(role);
const total=lessons.length,done=lessons.filter(l=>progress[l.id]).length;
return <main className="app-shell"><div className="ambient"/><div className="container"><nav className="nav"><Link href="/courses" className="brand">Skill<span>Arc</span></Link><Link href="/dashboard" className="btn">Dashboard</Link></nav><section className="page-head"><div className="eyebrow">{course.category??"Course"} · {course.level}</div><h1>{course.title}</h1><p>{course.description}</p>{!enrolled&&role==="student"&&<button className="btn primary" onClick={enroll}>Enroll in course</button>}{enrolled&&role==="student"&&<div className="tag">{done}/{total} lessons complete</div>}{canEdit&&<button className="btn primary" style={{marginLeft:10}} onClick={addModule}>+ Add module</button>}{message&&<div className="notice">{message}</div>}</section><div className="stack">{modules.map(m=><article className="card" key={m.id}><button className="module-button" onClick={()=>setOpen(open===m.id?null:m.id)}><span><b>{m.title}</b><small>{m.description}</small></span><span>{open===m.id?"−":"+"}</span></button>{open===m.id&&<div className="lesson-list">{lessons.filter(l=>l.module_id===m.id).map(l=><div className="lesson" key={l.id}><div><b>{l.title}</b><p>{l.content}</p></div>{role==="student"?<button className={"btn "+(progress[l.id]?"done":"")} onClick={()=>toggleLesson(l)}>{progress[l.id]?"Completed":"Mark complete"}</button>:null}</div>)}{canEdit&&<button className="btn" onClick={()=>addLesson(m.id)}>+ Add lesson</button>}</div>}</article>)}</div></div></main>}
