"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {createClient} from "@supabase/supabase-js";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
const roles=["super_admin","institute_admin","instructor","student","parent","business"];
export default function Admin(){const[users,setUsers]=useState<any[]>([]);const[allowed,setAllowed]=useState(false);const[canEdit,setCanEdit]=useState(false);const[loading,setLoading]=useState(true);const[msg,setMsg]=useState("");
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return;}const p=await supabase.from("profiles").select("role").eq("id",user.id).single();if(!["admin","super_admin","institute_admin"].includes(p.data?.role)){setLoading(false);return}setAllowed(true);setCanEdit(["admin","super_admin"].includes(p.data?.role));const{data,error}=await supabase.from("profiles").select("id,email,full_name,role,created_at,status,organization_id").order("created_at",{ascending:false});if(error)setMsg(error.message);setUsers(data??[]);setLoading(false)}
useEffect(()=>{load()},[]);
async function change(id:string,newRole:string){if(!canEdit)return;const{error}=await supabase.from("profiles").update({role:newRole}).eq("id",id);setMsg(error?error.message:"Role updated successfully.");load()}
if(loading)return <main className="app-shell"><div className="container"><div className="card" style={{marginTop:70}}>Loading administration center...</div></div></main>;
if(!allowed)return <main className="app-shell"><div className="container"><nav className="nav"><Link href="/dashboard" className="brand">Skill<span>Arc</span></Link></nav><div className="card" style={{marginTop:50}}><h2>Restricted workspace</h2><p>Administrator access is required.</p></div></div></main>;
return <main className="app-shell"><div className="ambient"/><div className="container"><nav className="nav"><Link href="/dashboard" className="brand">Skill<span>Arc</span></Link><Link href="/dashboard" className="btn">Dashboard</Link></nav><section className="page-head"><div className="eyebrow">Platform control</div><h1>Administration Center</h1><p>Manage identities, access levels and learning operations.</p></section><div className="stat-grid">{roles.map(r=><div className="stat" key={r}><b>{users.filter(u=>u.role===r).length}</b><span>{r.replace("_"," ")}</span></div>)}</div><div className="actions"><Link className="btn primary" href="/admin/courses">Course operations</Link><Link className="btn" href="/instructor">Teaching workspace</Link></div>{!canEdit&&<div className="notice">Institute administrators can review users within their organization. Platform-wide role changes require Super Admin access.</div>}<div className="card table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Created</th><th>Access</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.full_name||"Unnamed user"}</b><br/><span style={{color:"#707a8d"}}>{u.email}</span></td><td><span className="tag">{u.role}</span></td><td>{u.status||"active"}</td><td>{new Date(u.created_at).toLocaleDateString()}</td><td>{canEdit?<select value={u.role} onChange={e=>change(u.id,e.target.value)}>{roles.map(r=><option key={r} value={r}>{r.replace("_"," ")}</option>)}</select>:<span>View only</span>}</td></tr>)}</tbody></table></div>{msg&&<div className="notice">{msg}</div>}</div></main>}
