"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {createClient} from "@supabase/supabase-js";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
export default function Institute(){
 const[profile,setProfile]=useState<any>(null);const[students,setStudents]=useState(0);const[instructors,setInstructors]=useState(0);const[parents,setParents]=useState(0);const[courses,setCourses]=useState(0);const[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return;}const{data:p}=await supabase.from("profiles").select("id,full_name,role,organization_id").eq("id",user.id).single();setProfile(p);
  if(p?.organization_id){const org=p.organization_id;const[r1,r2,r3,r4]=await Promise.all([supabase.from("profiles").select("id",{count:"exact",head:true}).eq("organization_id",org).eq("role","student"),supabase.from("profiles").select("id",{count:"exact",head:true}).eq("organization_id",org).eq("role","instructor"),supabase.from("profiles").select("id",{count:"exact",head:true}).eq("organization_id",org).eq("role","parent"),supabase.from("courses").select("id",{count:"exact",head:true}).eq("organization_id",org)]);setStudents(r1.count??0);setInstructors(r2.count??0);setParents(r3.count??0);setCourses(r4.count??0)}setLoading(false)})()},[]);
 if(loading)return <main className="app-shell"><div className="container"><div className="card" style={{marginTop:70}}>Loading Institute Center...</div></div></main>;
 if(!profile||profile.role!=="institute_admin")return <main className="container"><div className="card" style={{marginTop:70}}><h2>Institute access required</h2><p>This center is restricted to institute administrators.</p></div></main>;
 return <main className="app-shell"><div className="ambient"/><div className="container"><nav className="nav"><Link href="/dashboard" className="brand">Skill<span>Arc</span></Link><Link href="/dashboard" className="btn">Dashboard</Link></nav><section className="page-head"><div className="eyebrow">Institute Administration</div><h1>Institute Center.</h1><p>Manage your organization's learning community from one workspace.</p></section><div className="stat-grid"><div className="stat"><b>{students}</b><span>Students</span></div><div className="stat"><b>{instructors}</b><span>Instructors</span></div><div className="stat"><b>{parents}</b><span>Parents</span></div><div className="stat"><b>{courses}</b><span>Courses</span></div></div><div className="grid" style={{marginTop:24}}><Link className="card link-card" href="/admin"><h3>People & roles →</h3><p>Review users and role assignments.</p></Link><Link className="card link-card" href="/admin/courses"><h3>Course operations →</h3><p>Manage your institute's course catalog.</p></Link><div className="card"><div className="tag">Governance</div><h3>Organization isolated</h3><p>Institute data is scoped to the authenticated administrator's organization.</p></div></div></div></main>