"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {createClient} from "@supabase/supabase-js";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
export default function AdminCourses(){const[courses,setCourses]=useState<any[]>([]);const[allowed,setAllowed]=useState(false);const[orgId,setOrgId]=useState<string|null>(null);const[form,setForm]=useState({title:"",description:"",category:"",level:"Beginner"});const[msg,setMsg]=useState("");
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return;}const{data:p}=await supabase.from("profiles").select("role,organization_id").eq("id",user.id).single();if(!["admin","super_admin","institute_admin"].includes(p?.role))return;setAllowed(true);setOrgId(p?.organization_id??null);let q=supabase.from("courses").select("*").order("created_at",{ascending:false});if(p?.role==="institute_admin"&&p.organization_id)q=q.eq("organization_id",p.organization_id);const{data}=await q;setCourses(data??[])}
useEffect(()=>{load()},[]);
async function createCourse(e:React.FormEvent){e.preventDefault();if(!orgId){setMsg("A course organization is required.");return;}const{error}=await supabase.from("courses").insert({...form,status:"published",organization_id:orgId});setMsg(error?error.message:"Course created successfully.");if(!error){setForm({title:"",description:"",category:"",level:"Beginner"});load()}}
async function archive(id:string){const{error}=await supabase.from("courses").update({status:"archived"}).eq("id",id);setMsg(error?error.message:"Course archived.");load()}
if(!allowed)return <main className="container"><div className="card" style={{marginTop:60}}><h2>Administrator access required</h2></div></main>;
return <main className="container"><nav className="nav"><Link href="/admin" className="brand">Skill<span>Arc</span></Link><Link href="/dashboard" className="btn">Dashboard</Link></nav><section className="page-head"><div className="eyebrow">Administration</div><h1>Course Management</h1><p>Manage courses within your organization and keep the catalog secure.</p></section><div className="card"><h3>Create a course</h3><form onSubmit={createCourse}><label>Course title</label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><label>Description</label><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label>Category</label><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><label>Level</label><select value={form.level} onChange={e=>setForm({...form,level:e.target.value})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><button className="btn primary" style={{marginTop:18}}>Create course</button></form>{msg&&<div className="notice">{msg}</div>}</div><div className="stack" style={{marginTop:20}}>{courses.map(c=><article className="card" key={c.id}><div className="tag">{c.status} · {c.level}</div><h3>{c.title}</h3><p>{c.description}</p>{c.status!=="archived"&&<button className="btn" onClick={()=>archive(c.id)}>Archive course</button>}</article>)}</div></main>}
