"use client";
import {useEffect,useMemo,useState} from "react";import Link from "next/link";import {createClient} from "@supabase/supabase-js";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
const statuses=["submitted","reviewing","shortlisted","rejected","hired"];
export default function Business(){
 const[account,setAccount]=useState<any>(null),[jobs,setJobs]=useState<any[]>([]),[applications,setApplications]=useState<any[]>([]),[candidates,setCandidates]=useState<any[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[form,setForm]=useState({title:"",description:"",location:"",employment_type:"Full-time",skills:""});
 async function load(){
  const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return;}
  const{data:ba}=await supabase.from("business_accounts").select("id,organization_id,company_name,contact_name,contact_email").eq("contact_email",user.email).maybeSingle();
  if(!ba){setAccount(null);setLoading(false);return;}setAccount(ba);
  const{data:j}=await supabase.from("job_postings").select("*").eq("organization_id",ba.organization_id).order("created_at",{ascending:false});setJobs(j??[]);
  if(j?.length){const ids=j.map((x:any)=>x.id);const{data:a}=await supabase.from("job_applications").select("id,job_id,candidate_id,status,cover_note,created_at").in("job_id",ids).order("created_at",{ascending:false});const apps=a??[];setApplications(apps);
   const candidateIds=[...new Set(apps.map((x:any)=>x.candidate_id))];if(candidateIds.length){const{data:cp}=await supabase.from("candidate_profiles").select("*").in("profile_id",candidateIds);const{data:p}=await supabase.from("profiles").select("id,full_name,email").in("id",candidateIds);setCandidates((cp??[]).map((c:any)=>({...c,profile:(p??[]).find((x:any)=>x.id===c.profile_id)})));}
  }else{setApplications([]);setCandidates([])}setLoading(false);
 }
 useEffect(()=>{load()},[]);
 async function createJob(){const{data:{user}}=await supabase.auth.getUser();if(!user||!account)return;const{error}=await supabase.from("job_postings").insert({organization_id:account.organization_id,posted_by:user.id,title:form.title,description:form.description,location:form.location,employment_type:form.employment_type,skills:form.skills.split(",").map(s=>s.trim()).filter(Boolean),status:"open"});if(!error){setForm({title:"",description:"",location:"",employment_type:"Full-time",skills:""});load();}}
 async function updateStatus(id:string,status:string){const{error}=await supabase.from("job_applications").update({status}).eq("id",id);if(!error)load();}
 const matched=useMemo(()=>candidates.filter(c=>{const q=search.toLowerCase().trim();if(!q)return true;return [c.headline,c.bio,c.education,c.experience,...(c.skills??[]),c.profile?.full_name].filter(Boolean).join(" ").toLowerCase().includes(q)}),[candidates,search]);
 if(loading)return <main className="app-shell"><div className="container"><div className="card" style={{marginTop:70}}>Loading Business Hub...</div></div></main>;
 return <main className="app-shell"><div className="ambient"/><div className="container"><nav className="nav"><Link href="/dashboard" className="brand">Skill<span>Arc</span></Link><Link href="/dashboard" className="btn">Dashboard</Link></nav>
 <section className="page-head"><div className="eyebrow">Business · Talent</div><h1>{account?account.company_name:"Business Hub"}</h1><p>Build your company presence, publish opportunities and move qualified candidates through a simple hiring pipeline.</p></section>
 {!account?<div className="card"><h3>Business account setup needed</h3><p>Your business login must be linked to a SkillArc business account before recruiting tools can be used.</p></div>:<>
 <div className="stat-grid"><div className="stat"><b>{jobs.length}</b><span>Job posts</span></div><div className="stat"><b>{applications.length}</b><span>Applications</span></div><div className="stat"><b>{jobs.filter((j:any)=>j.status==="open").length}</b><span>Open roles</span></div><div className="stat"><b>{applications.filter((a:any)=>a.status==="shortlisted").length}</b><span>Shortlisted</span></div></div>
 <div className="grid" style={{marginTop:24}}><section className="card"><div className="tag">Recruiting</div><h3>Post a job</h3><input placeholder="Job title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="Job description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><select value={form.employment_type} onChange={e=>setForm({...form,employment_type:e.target.value})}><option>Full-time</option><option>Part-time</option><option>Contract</option><option>Internship</option></select><input placeholder="Skills, comma separated" value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})}/><button className="btn primary" onClick={createJob} disabled={!form.title||!form.description}>Publish job</button></section>
 <section className="card"><div className="tag">Your openings</div><h3>Jobs</h3>{jobs.length?<div className="stack">{jobs.map((j:any)=><div className="lesson" key={j.id}><b>{j.title}</b><span>{j.location||"Remote"} · {j.employment_type} · {j.status}</span><small>{(j.skills??[]).join(" · ")}</small></div>)}</div>:<p>No job posts yet.</p>}</section></div>
 <section className="card" style={{marginTop:24}}><div className="tag">Talent discovery</div><h3>Candidate profiles</h3><input placeholder="Search by name, skill, education or experience" value={search} onChange={e=>setSearch(e.target.value)}/>{matched.length?<div className="grid" style={{marginTop:16}}>{matched.slice(0,12).map((c:any)=><div className="lesson" key={c.profile_id}><b>{c.profile?.full_name||"SkillArc candidate"}</b><span>{c.headline||"Candidate profile"}</span><small>{(c.skills??[]).join(" · ")}</small><small>{c.education||"Education not listed"} · {c.availability||"Availability not listed"}</small>{c.portfolio_url&&<a href={c.portfolio_url} target="_blank" rel="noreferrer" className="btn">Portfolio</a>}</div>)}</div>:<p>No candidate profiles match your search.</p>}</section>
 <section className="card" style={{marginTop:24}}><div className="tag">Pipeline</div><h3>Candidate applications</h3>{applications.length?<div className="table-wrap"><table><thead><tr><th>Candidate</th><th>Job</th><th>Status</th><th>Applied</th><th>Move</th></tr></thead><tbody>{applications.map((a:any)=>{const c=candidates.find((x:any)=>x.profile_id===a.candidate_id);return <tr key={a.id}><td>{c?.profile?.full_name||a.candidate_id.slice(0,8)+"…"}</td><td>{jobs.find((j:any)=>j.id===a.job_id)?.title??"Job"}</td><td><span className="tag">{a.status}</span></td><td>{new Date(a.created_at).toLocaleDateString()}</td><td><select value={a.status} onChange={e=>updateStatus(a.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></td></tr>})}</tbody></table></div>:<p>No applications yet.</p>}</section>
 </>}</div></main>
}